name: Deploy Website ke Hosting Arenhost
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
    - name: Ambil kode terbaru dari GitHub
      uses: actions/checkout@v4

    - name: Upload via FTP Utama Pasif
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: /public_html/deploypengumuman/
        state-name: .ftp-deploy-syncstate.json
        timeout: 900000
        exclude: |
          **/*.zip
          **/*.rar
          .git*
          .git*/**