name: Deploy Website ke Hosting Arenhost
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
    - name: Ambil kode terbaru dari GitHub
      uses: actions/checkout@v4

    - name: Upload via FTP Mode Pasif
      uses: Ishmael/ftp-deploy-action@v4.3.7
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ./pengumumanfix/
        passive: true # Memaksa koneksi menggunakan mode pasif agar lolos firewall hosting