name: Deploy Website via SFTP Super Stabil
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
    - name: Ambil kode terbaru dari GitHub
      uses: actions/checkout@v4

    - name: Upload via SFTP (Secure FTP)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: /public_html/deploypengumuman/